export const UPDATE_RADIO_INPUT = "UPDATE_RADIO_INPUT";
export const UPDATE_CHECKBOX_INPUT = "UPDATE_CHECKBOX_INPUT";
export const UPDATE_TEXT_INPUT = "UPDATE_TEXT_INPUT";
export const UPDATE_INPUT = "UPDATE_INPUT"
